apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argocd
  namespace: argocd
  annotations:
    # This tells Image Updater what to watch
    argocd-image-updater.argoproj.io/image-list: docker.io/vivekdalsaniya/doctor_finder
    argocd-image-updater.argoproj.io/yourname_myapp.update-strategy: latest
    argocd-image-updater.argoproj.io/vivekdalsaniya_doctor_finder.allow-tags: regexp:^\\d+$
spec:
  project: default
  source: 
    repoURL: https://github.com/vivekdalsaniya12/argocd.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ns
  syncPolicy:
    automated:  # <-- enables auto-sync
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # optional if deploying to non-existing namespace
