kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: nginx-ns
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-container
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: docker.io/vivekdalsaniya/nginx-web:35
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "125m"
            memory: "150Mi"
          limits:
            cpu: "225m"
            memory: "250Mi"
