kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: nginx-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-container
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: docker.io/vivekdalsaniya/nginx-web:35
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "5m"
            memory: "5Mi"
          limits:
            cpu: "10m"
            memory: "10Mi"
