kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginx-service 
  namespace: nginx-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30003
    targetPort: 80
